name: import_sorter
description: Automatically sort all your dart imports. Support for any dart project.
version: 4.2.1
repository: 'https://github.com/Matt-Gleich/import_sorter'
homepage: 'https://mattglei.ch'
maintainer: Matthew Gleich (@Matt-Gleich)
authors:
  - Matthew Gleich <matthewgleich@gmail.com>
  - Flutter Community <community@flutter.zone>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.6.0
  colorize: ^2.0.0
  petitparser: ^3.1.0
  yaml: ^2.2.0

dev_dependencies:
  test: ^1.14.3

import_sorter:
  emojis: true
